### ISSUE TITLE
Arm64 support

### ISSUE THREAD

**Issue by paolosezart** [assafmo/joincap#4]
I rummaged through several programs and scripts to combine pcap files, but your program is the best. I mainly use Kali Nethunter on an android phone and I would like to have this tool on it as well. Could you release an implementation for arm64? Since I have zero in compilation, but I haven’t found any ready-made solutions on the Internet. Thanks in advance.

**Comment by assafmo** [comment]
Yeah, sure. Just a few minutes.

**Comment by assafmo** [comment]
Here you go @paolosezart, let me know how it works for you. :relaxed: 
[joincap-linux-arm64-v0.10.1.zip](https://github.com/assafmo/joincap/files/4275819/joincap-linux-arm64-v0.10.1.zip)

**Comment by paolosezart** [comment]
Thanks a lot, everything works great. I downloaded the file from your link, unzipped it, renamed it to joincap and moved it to /usr/bin. The speed is excellent, as well as the ability to combine without specifying the name of the input files. Are you planning to add pcapng support in the program? Mergecap has this feature.

**Comment by assafmo** [comment]
No, I'm not planning to add `pcapng` support right now. It was easier for me to convert `pcapng` to `pcap` with `editcap` than implementing it in `join cap`.
