### ISSUE TITLE
Limit on merged file

### ISSUE THREAD

**Issue by AfakTolgi** [assafmo/joincap#7]
There can also be a limit of number of packets that can be merged or limit on size of merged file i.e merged file should not be greater then specified limit

**Comment by assafmo** [comment]
What do you mean, that you want to add a feature to limit the number of files and the number of packets per file?

**Comment by AfakTolgi** [comment]
My limit i mean 
eg: file1.pcap -> 5 packets
file2.pcap -> 5 packets
joincap file1.pcap file2.pcap -o merged.pcap -limit 7
merged.pcap should have 7 packets instead of 10 packets

**Comment by assafmo** [comment]
I think this should work:
```sh
joincap -w - file1.pcap file2.pcap | editcap -r /dev/stdin out.pcap 1-7
```

**Comment by AfakTolgi** [comment]
I was thinking of something inbuilt in joincap
